// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCusdVHxUniFAQfQGJ9e-RqNswYanPHBGE',
    appId: '1:272270147263:web:3dd5b0ce6405466b7a100a',
    messagingSenderId: '272270147263',
    projectId: 'task-pair-app',
    authDomain: 'task-pair-app.firebaseapp.com',
    storageBucket: 'task-pair-app.firebasestorage.app',
    measurementId: 'G-YV9WBB8LQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZ0NpoW_13fi4obPRB66k9WZFK1Tzv08',
    appId: '1:272270147263:android:ba455e014288c2ba7a100a',
    messagingSenderId: '272270147263',
    projectId: 'task-pair-app',
    storageBucket: 'task-pair-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBH-FUup_eKmsSbT3291am9l1qyFrdQfw',
    appId: '1:272270147263:ios:90354746485cbc407a100a',
    messagingSenderId: '272270147263',
    projectId: 'task-pair-app',
    storageBucket: 'task-pair-app.firebasestorage.app',
    androidClientId: '272270147263-svpveknd80ct79u4e2c0jhhos3cs6ucn.apps.googleusercontent.com',
    iosClientId: '272270147263-kiieqsg6u4d1d3cvotmfsl98h4vjsik4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskPairApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBH-FUup_eKmsSbT3291am9l1qyFrdQfw',
    appId: '1:272270147263:ios:90354746485cbc407a100a',
    messagingSenderId: '272270147263',
    projectId: 'task-pair-app',
    storageBucket: 'task-pair-app.firebasestorage.app',
    androidClientId: '272270147263-svpveknd80ct79u4e2c0jhhos3cs6ucn.apps.googleusercontent.com',
    iosClientId: '272270147263-kiieqsg6u4d1d3cvotmfsl98h4vjsik4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskPairApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCusdVHxUniFAQfQGJ9e-RqNswYanPHBGE',
    appId: '1:272270147263:web:94b0323858bb06c17a100a',
    messagingSenderId: '272270147263',
    projectId: 'task-pair-app',
    authDomain: 'task-pair-app.firebaseapp.com',
    storageBucket: 'task-pair-app.firebasestorage.app',
    measurementId: 'G-KQL21NTZ90',
  );
}
